#!/bin/bash

# BKMS Help Script - Shows all available commands

echo "================================================"
echo "🚀 Bayesian Knowledge Management System (BKMS)"
echo "   Available Commands"
echo "================================================"
echo ""
echo "📦 Database Management:"
echo "  ./clear-db.sh         - Clear database (with confirmation)"
echo "  cd app && node scripts/check-database.js"
echo "                        - Check database status"
echo "  cd app && node scripts/setup-constraints.js"
echo "                        - Setup database constraints (run once)"
echo ""
echo "🧪 Testing:"
echo "  See TEST_GUIDE.md     - Curl-based API tests"
echo ""
echo "💻 Development:"
echo "  cd app && npm run dev - Start development server"
echo "                          Open http://localhost:3000"
echo "  cd app && npm run build"
echo "                        - Build for production"
echo "  cd app && npm start   - Run production build"
echo ""
echo "📊 Neo4j Browser:"
echo "  http://localhost:7474 - Neo4j Browser interface"
echo "  Username: neo4j"
echo "  Password: neo4jneo4j"
echo ""
echo "📝 Quick Start:"
echo "  1. ./clear-db-force.sh  - Clear database"
echo "  2. cd app && node scripts/setup-constraints.js - Setup constraints"
echo "  3. cd app && npm run dev - Start the app"
echo "  4. Open http://localhost:3000"
echo ""
echo "🎯 Features:"
echo "  • Create and manage hypotheses with confidence levels"
echo "  • Add evidence and link to hypotheses"
echo "  • Automatic Bayesian probability updates"
echo "  • Verify/refute hypotheses with definitive evidence"
echo "  • Auto-generated IDs with collision detection"
echo "  • Full CRUD operations for hypotheses and evidence"
echo ""
echo "================================================"
